markdown: kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins: [jekyll-paginate]

# Setup
title:            CElander
tagline:          'I did a thing'
description:      'A site originally made in ENGL 460 in the Fall of 2017'
url:              https://ChaseElander.github.io
baseurl:          ''

author:
  name:           'Chase Elander'
  url:            https://github.com/oncomouse/engl460fall2017/blob/master/units/02-tools/07-jekyll/day20.md

paginate:         5


